#!/usr/bin/env bash

has_errors=0

# get go files to check against
gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
[ -z "$gofiles" ] && exit 0

show_vet_header=true
for file in $gofiles ; do
	vet=$(go vet $file 2>&1)
	if [ -n "$vet" -a $show_vet_header = true ] ; then
		echo "Go vet check results:"
		show_vet_header=false
	fi
	if [ -n "$vet" ] ; then
		echo "$vet\n"
		has_errors=1
	fi
done

exit $has_errors
